<a href="https://colab.research.google.com/github/Arijitde24/Machine-learning/blob/main/ML%20Projects/Recomendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy==1.26.4

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)

In [ ]:
!pip install scikit-surprise

Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.12/dist-packages (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.16.3)

In [ ]:
import numpy as np
import pandas as pd
from surprise import Reader,Dataset,SVD
from surprise.model_selection import cross_validate

In [ ]:
ratings = pd.read_csv("/content/drive/MyDrive/DATASETS/combined_data_1.txt",header=None,names=['Cust_ID','Rating'],usecols=[0,1])

In [ ]:
ratings

          Cust_ID  Rating
0              1:     NaN
1         1488844     3.0
2          822109     5.0
3          885013     4.0
4           30878     4.0
...           ...     ...
24058258  2591364     2.0
24058259  1791000     2.0
24058260   512536     5.0
24058261   988963     3.0
24058262  1704416     3.0

[24058263 rows x 2 columns]

In [ ]:
movie = pd.read_csv("/content/drive/MyDrive/DATASETS/movies.csv",encoding = "ISO-8859-1", usecols=[0,1,2])

In [ ]:
movie

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund fÃ¼r's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror

In [ ]:
movie_id = None
movie_np = []

for i in ratings['Cust_ID']:
    if ':' in i:
        movie_id = int(i.replace(':', ''))
    movie_np.append(movie_id)
movie_np

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [ ]:
ratings["Movie_ID"] = movie_np

In [ ]:
ratings

          Cust_ID  Rating  Movie_ID
0              1:     NaN         1
1         1488844     3.0         1
2          822109     5.0         1
3          885013     4.0         1
4           30878     4.0         1
...           ...     ...       ...
24058258  2591364     2.0      4499
24058259  1791000     2.0      4499
24058260   512536     5.0      4499
24058261   988963     3.0      4499
24058262  1704416     3.0      4499

[24058263 rows x 3 columns]

In [ ]:
ratings["Rating"].isnull().sum()

4499

In [ ]:
ratings["Movie_ID"].nunique()

4499

In [ ]:
ratings.dropna(inplace=True)

In [ ]:
ratings

          Cust_ID  Rating  Movie_ID
1         1488844     3.0         1
2          822109     5.0         1
3          885013     4.0         1
4           30878     4.0         1
5          823519     3.0         1
...           ...     ...       ...
24058258  2591364     2.0      4499
24058259  1791000     2.0      4499
24058260   512536     5.0      4499
24058261   988963     3.0      4499
24058262  1704416     3.0      4499

[24053764 rows x 3 columns]

In [ ]:
movie_summary=ratings["Movie_ID"].value_counts()

In [ ]:
movie_summary

Movie_ID
1905    193941
2152    162597
3860    160454
4432    156183
571     154832
         ...
4294        44
915         43
3656        42
4338        39
4362        36
Name: count, Length: 4499, dtype: int64

In [ ]:
rating_benchmark = round(movie_summary.quantile(0.6),0)

In [ ]:
rating_benchmark

908.0

In [ ]:
movie_id_rat = movie_summary[(movie_summary<=rating_benchmark)].index

In [ ]:
cust_sum = ratings['Cust_ID'].value_counts()

In [ ]:
cust_sum

Cust_ID
305344     4467
387418     4422
2439493    4195
1664010    4019
2118461    3769
           ...
1300341       1
2550360       1
11848         1
930788        1
594210        1
Name: count, Length: 470758, dtype: int64

In [ ]:
cust_benchmark = round(cust_sum.quantile(0.6),0)

In [ ]:
cust_benchmark

36.0

In [ ]:
movie_id_cust = cust_sum[(cust_sum<=rating_benchmark)].index

In [ ]:
ratings = ratings[(~ratings['Movie_ID'].isin(movie_id_cust)) & (~ratings['Cust_ID'].isin(movie_id_cust))]

In [ ]:
ratings

          Cust_ID  Rating  Movie_ID
26        1227322     4.0         1
32         786312     3.0         1
37         525356     2.0         1
61        1927580     4.0         1
85        1792741     2.0         1
...           ...     ...       ...
24058189   387418     2.0      4499
24058196  1114324     1.0      4499
24058203   794999     5.0      4499
24058204  1932594     1.0      4499
24058244  1852040     1.0      4499

[154204 rows x 3 columns]

In [ ]:
reader= Reader()

In [ ]:
data = Dataset.load_from_df(ratings[['Cust_ID','Movie_ID','Rating']][:100000],reader)
data

In [ ]:
filter_ratings = ratings.groupby('Movie_ID')['Rating'].mean().sort_values(ascending=False)

In [ ]:
filter_ratings

Movie_ID
2849    5.000000
13      5.000000
2412    4.500000
3962    4.278351
2862    4.276190
          ...
3790    1.000000
2537    1.000000
3603    1.000000
4433    1.000000
4294    1.000000
Name: Rating, Length: 4495, dtype: float64

In [ ]:
best_pop_gen_id = filter_ratings[filter_ratings>=4].index

In [ ]:
best_pop_gen_id

Index([2849,   13, 2412, 3962, 2862, 4306, 2452,  798, 3290, 3456, 2782, 3864,
        886, 3938, 1905,  205, 2562, 2142],
      dtype='int64', name='Movie_ID')

In [ ]:
popular_movies = movie[movie['movieId'].isin(best_pop_gen_id)]

In [ ]:
popular_movies

,movieId,title,genres
12,13,Balto (1995),Adventure|Animation|Children
203,205,Unstrung Heroes (1995),Comedy|Drama
785,798,Daylight (1996),Action|Adventure|Drama|Thriller
869,886,Bulletproof (1996),Action|Comedy|Crime
1821,1905,Marie from the Bay of Angels (Marie Baie Des A...,Drama
2058,2142,"American Tail: Fievel Goes West, An (1991)",Adventure|Animation|Children|Musical|Western
2327,2412,Rocky V (1990),Action|Drama
2367,2452,"Gate II: Trespassers, The (1990)",Horror
2477,2562,Bandits (1997),Drama
2696,2782,"Pit and the Pendulum, The (1961)",Horror
2763,2849,Queens Logic (1991),Comedy|Drama
2776,2862,Caligula (1979),Drama
3203,3290,Soft Toilet Seats (1999),Comedy
3367,3456,"Color of Paradise, The (Rang-e khoda) (1999)",Drama
3771,3864,Godzilla 2000 (Gojira ni-sen mireniamu) (1999),Action|Adventure|Sci-Fi
3844,3938,"Slumber Party Massacre, The (1982)",Horror
3868,3962,Ghoulies II (1987),Comedy|Horror
4211,4306,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...

In [ ]:
best_rated_genres = popular_movies.merge(
    filter_ratings, left_on='movieId', right_index=True
).sort_values(by='Rating', ascending=False).reset_index(drop=True)

In [ ]:
best_rated_genres

,movieId,title,genres,Rating
0,13,Balto (1995),Adventure|Animation|Children,5.000000
1,2849,Queens Logic (1991),Comedy|Drama,5.000000
2,2412,Rocky V (1990),Action|Drama,4.500000
3,3962,Ghoulies II (1987),Comedy|Horror,4.278351
4,2862,Caligula (1979),Drama,4.276190
5,4306,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...,4.254717
6,2452,"Gate II: Trespassers, The (1990)",Horror,4.219048
7,798,Daylight (1996),Action|Adventure|Drama|Thriller,4.144231
8,3290,Soft Toilet Seats (1999),Comedy,4.131313
9,3456,"Color of Paradise, The (Rang-e khoda) (1999)",Drama,4.125000
10,2782,"Pit and the Pendulum, The (1961)",Horror,4.117647
11,3864,Godzilla 2000 (Gojira ni-sen mireniamu) (1999),Action|Adventure|Sci-Fi,4.108108
12,886,Bulletproof (1996),Action|Comedy|Crime,4.105882
13,3938,"Slumber Party Massacre, The (1982)",Horror,4.096774
14,1905,Marie from the Bay of Angels (Marie Baie Des A...,Drama,4.038835
15,2142,"American Tail: Fievel Goes West, An (1991)",Adventure|Animation|Children|Musical|Western,4.000000
16,2562,Bandits (1997),Drama,4.000000
17,205,Unstrung Heroes (1995),Comedy|Drama,4.000000

In [ ]:
worst_gen_id = filter_ratings[filter_ratings<2.5].index

In [ ]:
bad_movies = movie[movie['movieId'].isin(worst_gen_id)]

In [ ]:
worst_rated_genres = bad_movies.merge(
    filter_ratings, left_on='movieId', right_index=True
).sort_values(by='Rating', ascending=False).reset_index(drop=True)

In [ ]:
worst_rated_genres

,movieId,title,genres,Rating
0,2828,Dudley Do-Right (1999),Children|Comedy,2.491525
1,3000,Princess Mononoke (Mononoke-hime) (1997),Action|Adventure|Animation|Drama|Fantasy,2.491228
2,2423,Christmas Vacation (National Lampoon's Christm...,Comedy,2.491228
3,3595,Held Up (1999),Comedy,2.491228
4,1142,Get Over It (1996),Drama,2.489796
...,...,...,...,...
2228,3790,Groove (2000),Drama,1.000000
2229,753,"Month by the Lake, A (1995)",Comedy|Drama|Romance,1.000000
2230,4373,Pootie Tang (2001),Comedy,1.000000
2231,1979,Friday the 13th Part VI: Jason Lives (1986),Horror,1.000000
2232,3603,"Gay Deceivers, The (1969)",Comedy,1.000000

In [ ]:
model = SVD(random_state=42)
cross_validate(model,data,measures=['RMSE','MAE'],cv=3)

{'test_rmse': array([0.93469132, 0.93802896, 0.92614107]),
 'test_mae': array([0.71339011, 0.71368142, 0.70672546]),
 'fit_time': (1.748476505279541, 1.7378344535827637, 1.3011629581451416),
 'test_time': (0.33632969856262207, 0.42122864723205566, 0.40747642517089844)}

In [ ]:
def reccomend(id,n=5):
    user = movie.copy()
    user = user[(~user['movieId'].isin(movie_id_rat))]
    user['Estimate'] = user['movieId'].apply(lambda x: model.predict(id,x).est)
    return user.sort_values('Estimate',ascending=False)[['movieId', 'title', 'Estimate']].head(n)

In [ ]:
reccomend(1331154)

      movieId                             title  Estimate
2367     2452  Gate II: Trespassers, The (1990)  4.251697
2776     2862                   Caligula (1979)  4.170483
785       798                   Daylight (1996)  4.081114
2696     2782  Pit and the Pendulum, The (1961)  4.038561
869       886                Bulletproof (1996)  3.941835

In [ ]:
def dont_reccomend(id,n=5):
    user = movie.copy()
    user = user[(~user['movieId'].isin(movie_id_rat))]
    user['Estimate'] = user['movieId'].apply(lambda x: model.predict(id,x).est)
    return user.sort_values('Estimate',ascending=False)[['movieId', 'title', 'Estimate']].tail(n)

In [ ]:
dont_reccomend(1331154)

      movieId                                     title  Estimate
1265     1293                             Gandhi (1982)  2.245116
2607     2693                           Trekkies (1997)  2.209760
1078     1100                    Days of Thunder (1990)  2.164164
1907     1991                       Child's Play (1988)  2.106699
2191     2276  Soldier's Daughter Never Cries, A (1998)  2.058101